Menu();

function Menu() {
    document.open();
    document.write("<div id='wrapper'>");
    document.write("<div id='sidebar'>");
    document.write("<div id='sidebarWrap'>");
    document.write("<h1><a href='index.html' class='logo'><img src='images/logo.png' width='100%' alt='logo'></a></h1>");
    document.write("<nav id='mainnav'>");
    document.write("<p id='menuWrap'><a id='menu'><span id='menuBtn'></span></a></p>");
    document.write("<div class='panel'>");
    document.write("<div class='border-wrap'>");
    document.write("<ul class='rotateY'>");
    document.write("<li><a href='index.html'>トップ</a></li>");
    document.write("<li class='modslist1'><a>導入MOD▼</a></li>");
    document.write("</ul>");
    document.write("<ul class='modslist'>");
    document.write("<li><a href='tech.html'>工業MOD</a></li>");
    document.write("<li><a href='magic.html'>魔術MOD</a></li>");
    document.write("<li><a href='farming.html'>農業MOD</a></li>");
    document.write("<li><a href='exploration.html'>探検MOD</a></li>");
    document.write("<li><a href='building.html'>建築MOD</a></li>");
    document.write("<li><a href='othermods.html'>その他MOD</a></li>");
    document.write("</ul>");
    document.write("<ul>");
    document.write("<li><a href='sns.html'>鯖民の動画</a></li>");
    document.write("<li><a href='join.html'>参加方法</a></li>");
    document.write("<li><a href='event.html'>イベント</a></li>");
    document.write("<li><a href='donate.html'>寄付</a></li>");
    document.write("<li class='infotab1'><a>情報▼</a></li>");
    document.write("</ul>");
    document.write("<ul class='infotab'><li><a href='rule.html'>ルール </a></li>");
    document.write("<li><a href='tutorial.html'>㊙情報</a></li>");
    document.write("<li><a href='hobby.html'>娯楽施設</a></li>");
    document.write("<li><a href='dev.html'>開発陣一覧</a></li>");
    document.write("<li><a href='stats.html'>ムスカリ統計局</a></li>");
    document.write("<li><a href='command.html'>コマンド一覧</a></li>");
    document.write("<li><a href='calender.html'>予定表</a></li>");
    document.write("<li><a href='faq.html'>よくある質問</a></li>");
    document.write("<li><a href='bug.html'>既知のバグ</a></li>");
    document.write("<li><a href='spec.html'>サーバースペック</a></li>");
    document.write("<li><a href='memory.html'>記録</a></li>");
    document.write("</ul>");
    document.write("<ul>");
    document.write("<li><a href='rct.html'>開発陣募集</a></li>");
    document.write("<li><a href='link.html'>リンク集</a></li>");
    document.write("<li><a href='http://muscari.fun:8123/'>Dynmap</a></li>");
    document.write("</ul>");
    document.write("</div>");
    document.write("<ul id='sns'>");
    document.write("<li><a href='https://twitter.com/taisa_ism' target='_blank' class='twitter'><img src='images/iconTw.png' width='20' height='20' alt='twitter'></a></li>");
    document.write("<li><a href='https://monocraft.net/servers/kypYX49aMGbHh1i47yH5/photos' target='_blank' class='monostagram'><img src='images/iconInsta.png' width='20' height='20' alt='Instagram'></a></li>");
    document.write("</ul>");
    document.write("<iframe class='discord' src='https://discord.com/widget?id=419146900441137173&theme=dark' width='350' height='420' allowtransparency='true' frameborder='0' sandbox='allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts'></iframe>");
    document.write("</div>");
    document.write("</nav>");
    document.write("</div>");
    document.write("</div>");
}
